export { default as DashboardView } from './DashboardView';
export { default as CustomerView } from './CustomerView';
export { default as InventoryView } from './InventoryView';
export { default as StockInView } from './StockInView';
export { default as POSSalesView } from './POSSalesView';
export { default as BillsManagementView } from './BillsManagementView';
export { default as StockAlertsView } from './StockAlertsView';
export { default as UserManagementView } from './UserManagementView';
export { default as ProfileView } from './ProfileView';
